server: 
 port: 7750
 

logging:
 level:
  ROOT: INFO
#storage:
# database:mongodb
#
#
#net:
# 27017
# enabled:true


spring.data.mongodb.database: arcadia_test
spring.data.mongodb.uri: mongodb://localhost:27017

spring.data.neo4j.uri: bolt://localhost
spring.data.neo4j.username : neo4j

