//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.06 at 11:22:17 AM EET 
//


package viseco.sc.model.document;

import viseco.sc.model.domain.ChainableEndpointCategory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ECEPID"/&gt;
 *         &lt;element name="AllowsMultipleTenants" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element ref="{}ChainableEndpointCategory"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ecepid",
    "allowsMultipleTenants",
    "chainableEndpointCategory"
})
@XmlRootElement(name = "ExposedChainableEndpoint")
public class ExposedChainableEndpoint {

    @XmlElement(name = "ECEPID", required = true)
    protected String ecepid;
    @XmlElement(name = "AllowsMultipleTenants")
    protected boolean allowsMultipleTenants;
    @XmlElement(name = "ChainableEndpointCategory", required = true)
    protected ChainableEndpointCategory chainableEndpointCategory;

    /**
     * Gets the value of the ecepid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECEPID() {
        return ecepid;
    }

    /**
     * Sets the value of the ecepid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECEPID(String value) {
        this.ecepid = value;
    }

    /**
     * Gets the value of the allowsMultipleTenants property.
     * 
     */
    public boolean isAllowsMultipleTenants() {
        return allowsMultipleTenants;
    }

    /**
     * Sets the value of the allowsMultipleTenants property.
     * 
     */
    public void setAllowsMultipleTenants(boolean value) {
        this.allowsMultipleTenants = value;
    }

    /**
     * Gets the value of the chainableEndpointCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ChainableEndpointCategory }
     *     
     */
    public ChainableEndpointCategory getChainableEndpointCategory() {
        return chainableEndpointCategory;
    }

    /**
     * Sets the value of the chainableEndpointCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChainableEndpointCategory }
     *     
     */
    public void setChainableEndpointCategory(ChainableEndpointCategory value) {
        this.chainableEndpointCategory = value;
    }

}
