//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.06 at 11:22:17 AM EET 
//


package viseco.sc.model.document;

import viseco.sc.model.domain.ChainableEndpointCategory;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ChainableEndpointCategory" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chainableEndpointCategory"
})
@XmlRootElement(name = "RequiredChainableEndpoints")
public class RequiredChainableEndpoints {

    @XmlElement(name = "ChainableEndpointCategory")
    protected List<ChainableEndpointCategory> chainableEndpointCategory;

    /**
     * Gets the value of the chainableEndpointCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chainableEndpointCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChainableEndpointCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChainableEndpointCategory }
     * 
     * 
     */
    public List<ChainableEndpointCategory> getChainableEndpointCategory() {
        if (chainableEndpointCategory == null) {
            chainableEndpointCategory = new ArrayList<ChainableEndpointCategory>();
        }
        return this.chainableEndpointCategory;
    }

}
